# site settings

title: Wesley Montserrat
description: 
taglong: Software Engineering | DevOps | Cybersecurity
tagshort: Software Engineering | DevOps | Cybersecurity
url: https://wesleyem.com
baseurl: ""
permalink: pretty
repo: https://github.com/wesleyem/wesleyem.com

# author settings
author:
  name: Wesley Montserrat
  email: wesleyem@proton.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: wesleyem
  linkedin: wesleymontserrat
  x: spo0f_

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
