# site settings

title: Wesley Montserrat
description: Empower Your Digital Environment with Wesley Montserrat, a Military Leader and Helicopter Pilot Transitioning to IT. Bringing a background in strategic planning, operational risk management, and cross-functional collaboration from the military, I am committed to excellence in process automation, information systems safeguarding, and effective leadership. Positioned to contribute strong leadership and a determined mindset to optimize your organization's processes. Connect with me to discover how my expertise can elevate your company's IT initiatives.
taglong: Military professional embarking on the next chapter, committed leader, and lifelong learner
tagshort: Military professional embarking on the next chapter, committed leader, and lifelong learner
url: https://wesleyem.com
baseurl: ""
permalink: pretty
repo: https://github.com/wesleyem/wesleyem.com

# author settings
author:
  name: Wesley Montserrat
  email: wesleyem@proton.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: wesleyem
  linkedin: wesleymontserrat
  x: spo0f_

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
